team:
  token: "cmd-demo-token-123"
  name: "Demo Squadron"
  planet-name: "Demo Prime"

game-server:
  base-url: "http://localhost:8080"

strategy:
  home-bias: 0.6
    
micronaut:
  http:
    services:
      game-server:
        url: ${game-server.base-url}
  serde:
    deserialization:
      fail-on-unknown-properties: true
  application:
    name: basestation
  server:
    port: 8081