team:
  token: "h4ck3rz-admin"
  name: "h4ck3rz"
  planet-name: "g3t_wr3ck3d 101"

game-server:
  base-url: "http://localhost:8080"

strategy:
  home-bias: 0.6

datasources:
  default:
    url: jdbc:h2:mem:teamdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

netty:
  default:
    allocator:
      type: unpooled

h2:
  console:
    enabled: true
    path: /h2-console
    
micronaut:
  http:
    services:
      game-server:
        url: ${game-server.base-url}
  serde:
    deserialization:
      fail-on-unknown-properties: true
  application:
    name: basestation
  server:
    port: 8081
  sql:
    datasources:
      default:
        schema-generate: NONE
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
